name: 'gaming_analytics'
version: '1.0.0'
config-version: 2

profile: 'gaming_analytics_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:       
  - "target"
  - "dbt_packages"

models:
  gaming_analytics:
    core:
      +materialized: table